### Numpy
##### It is much faster than compare to traditional Python list
##### The NumPy arrays takes significantly less amount of memory as compared to python lists.

In [9]:
import numpy as np
import sys

In [3]:
# numpy vs list (storage)
num=1000000

In [5]:
li=[]
li=[i for i in range(num)]

In [10]:
sys.getsizeof(li)

8448728

In [11]:
m=np.array(li)

In [12]:
sys.getsizeof(m)

4000096

In [248]:
# numpy vs list (time)
%timeit li=[i**3 for i in range(20)]

4.99 µs ± 133 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [249]:
%timeit num_li=np.arange(20)**3

1.41 µs ± 7.13 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


###### we can see numpy is faster than python list

In [22]:
# how to create an array in np
n=np.array([1,2,3,4])

In [16]:
n

array([1, 2, 3, 4])

In [17]:
type(n)

numpy.ndarray

In [18]:
n.ndim
# this gives us the dimension/rank of array

1

In [19]:
n.size
# total no. of elements in array

4

In [20]:
n.shape
# shape of array

(4,)

In [21]:
n.dtype
# datatype of array

dtype('int32')

In [24]:
# 2d array list of list
_2d=np.array([[1,2,3,4],[2,3,4,5]])

In [25]:
_2d

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [26]:
type(_2d)

numpy.ndarray

In [27]:
_2d.ndim

2

In [29]:
_2d.shape[0]

2

In [30]:
_2d.size

8

In [37]:
# 3d array list of(-->) list(-->) of list
_3d=np.array([[[1,2,3,4],[1,2,4,5],[2,3,4,3]]])

In [38]:
_3d

array([[[1, 2, 3, 4],
        [1, 2, 4, 5],
        [2, 3, 4, 3]]])

In [39]:
_3d.ndim

3

In [40]:
_3d.size

12

In [41]:
# ones
ones=np.array([[1,1,1],[1,1,1]])

In [42]:
ones

array([[1, 1, 1],
       [1, 1, 1]])

In [192]:
# np.ones(2).ndim
np.ones(2)
# Return a new array of given shape and type(by default it is float), filled with ones.

array([1., 1.])

In [45]:
np.ones((2,2),dtype='int32')

array([[1, 1],
       [1, 1]])

In [46]:
np.ones((2,2),dtype='object')
# (2-->row,2-->column) we are creating an array that has 2 rows and 2 columns.

array([[1, 1],
       [1, 1]], dtype=object)

In [47]:
np.zeros(4)
# Return a new array of given shape and type(by default it is float), filled with zeros.

array([0., 0., 0., 0.])

In [193]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [195]:
# identity matrix
np.eye((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [197]:
np.zeros((1,3,4))
# (1-->depth,3-->rows,4-->column)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [51]:
np.zeros((5,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [199]:
# np.full((2,3),3).ndim --> 2
np.full((2,3),0)
# # Return a new array of given shape and type, filled with particular values

array([[0, 0, 0],
       [0, 0, 0]])

In [201]:
# arange()-->It returns the ndarray object containing evenly spaced values within the given range 
# arange(start(by default 0), stop, steps(by default 1))
np.arange(2,10,2)

array([2, 4, 6, 8])

In [202]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [203]:
ar=np.arange(10)
len(ar)

10

In [83]:
# reshape()-->this function shapes an array without changing the data of the array.
res=ar.reshape(1,2,5)

In [204]:
res

array([[[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]])

In [205]:
res.ndim

3

In [207]:
# res.reshape(-1)-->flatten the array(convert it into 1D array)
res.reshape(10) #same as above code

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
# np.ravel(res).ndim --> 1
np.ravel(res) # Return a contiguous flattened array.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
arr2=np.arange(10).reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
arr2.shape

(2, 5)

In [210]:
# transpose
m2=arr2.T
m2

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [93]:
m2.shape

(5, 2)

In [228]:
a1=np.arange(10).reshape(2,5)
a2=np.arange(10,20).reshape(2,5)

In [100]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [101]:
a2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [102]:
a1+a2

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [103]:
np.add(a1,a2)
# add two array

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [104]:
np.subtract(a1,a2)

array([[-10, -10, -10, -10, -10],
       [-10, -10, -10, -10, -10]])

In [107]:
np.divide(a1,a2)

array([[0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429],
       [0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421]])

In [108]:
np.multiply(a1,a2)

array([[  0,  11,  24,  39,  56],
       [ 75,  96, 119, 144, 171]])

In [222]:
newa1=np.arange(9).reshape(3,3)
newa2=np.arange(3).reshape(3,1)
print(newa1,'\n')
print(newa2,'\n')
print("dimension of array1 row ", newa1[0].ndim)
print("dimension of array2 column ",newa2[0:,0].ndim)
np.dot(newa1,newa2) #The number of columns of the 1st array must equal the number of rows of the 2nd array.
# alternate newa1 @ newa2

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[0]
 [1]
 [2]] 

dimension of array1 row  1
dimension of array2 column  1


array([[ 5],
       [14],
       [23]])

In [230]:
a11=np.array([1,2,3,4])
a22=np.array([3,2,3,4])

In [231]:
a11 @ a22
#dot product 1.3 + 2.2 + 3.3 + 4.4 --> 3+4+9+16 = 32

32

In [233]:
# a11.dot(a22)-->32
np.dot(a11,a22)

32

In [226]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

In [229]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [121]:
a1.max()
# gives max element from array

9

In [122]:
# axis=0 column
# axis=1 row

In [234]:
a1.max(axis=1)

array([4, 9])

In [124]:
a1.max(axis=0)

array([5, 6, 7, 8, 9])

In [125]:
a1.argmax()
# gives index of max elemnt

9

In [236]:
a1.min()
# gives min element from array

0

In [127]:
a1.argmin()
# gives index of min element

0

In [128]:
np.mean(a1)

4.5

In [238]:
np.sum(a1)

45

In [130]:
np.sum(a1,axis=1)

array([10, 35])

In [239]:
np.sum(a1,axis=0)

array([ 5,  7,  9, 11, 13])

In [240]:
np.std(a1)

2.8722813232690143

In [241]:
np.log(a1)

<ipython-input-241-f50b4f369011>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458]])

In [135]:
np.log10(a1)

<ipython-input-135-c2fb83293004>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a1)


array([[      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251]])

## Slicing in Numpy

In [136]:
sl=np.arange(10)

In [137]:
sl

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [140]:
sl[1].ndim

0

In [141]:
sl[3].ndim

0

In [142]:
sl=np.arange(10).reshape(2,5)

In [150]:
sl
# sl.shape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [144]:
# [row,colum]
sl[0]

array([0, 1, 2, 3, 4])

In [145]:
sl[1]

array([5, 6, 7, 8, 9])

In [146]:
sl[0,1]

1

In [148]:
sl[1,2]

7

In [152]:
sl[0:2,1:3] #--> 0 1 1 2

array([[1, 2],
       [6, 7]])

In [153]:
sl[0:2,1:3].ndim

2

In [161]:
sl2=np.arange(100)
sl3=sl2.reshape(10,10)

In [163]:
sl3.ndim
sl3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [164]:
sl3[1:3,4:6]

array([[14, 15],
       [24, 25]])

In [166]:
sl3[3:5,3:6]

array([[33, 34, 35],
       [43, 44, 45]])

In [167]:
sl3[3:6,3:5]


array([[33, 34],
       [43, 44],
       [53, 54]])

In [243]:
sl3[0::2,:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [244]:
sl3[0:,0::2]

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [168]:
sl4=np.arange(50).reshape(2,5,5)

In [170]:
sl4

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [171]:
sl4[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [172]:
sl4[1]

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [179]:
sl4[0:2,0]

array([[ 0,  1,  2,  3,  4],
       [25, 26, 27, 28, 29]])

In [180]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [182]:
a2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [245]:
# Merge arrays, by default axis=0
np.concatenate((a1,a2,a1),axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [246]:
np.concatenate((a1,a2),axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [247]:
np.vstack((a1,a2)) #vwertical stack same as np.concatenate((a1,a2),axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [191]:
np.hstack((a1,a2)) #horizontal stack same as np.concatenate((a1,a2),axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [ ]:
# Break